
default: &default
  adapter: postgresql
  encoding: unicode
  username: blog
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: blog
  password: password
  database: blog_development

test:
  <<: *default
  username: blog
  password: password
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: blog
  password: password
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
